package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSCardorder<M extends BaseSCardorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

	public void setCardId(java.lang.Long cardId) {
		set("card_id", cardId);
	}

	public java.lang.Long getCardId() {
		return get("card_id");
	}

	public void setCardName(java.lang.String cardName) {
		set("card_name", cardName);
	}

	public java.lang.String getCardName() {
		return get("card_name");
	}

	public void setMonthcardId(java.lang.Long monthcardId) {
		set("monthcard_id", monthcardId);
	}

	public java.lang.Long getMonthcardId() {
		return get("monthcard_id");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAmountVolume(java.math.BigDecimal amountVolume) {
		set("amount_volume", amountVolume);
	}

	public java.math.BigDecimal getAmountVolume() {
		return get("amount_volume");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setKsl(java.lang.Integer ksl) {
		set("ksl", ksl);
	}

	public java.lang.Integer getKsl() {
		return get("ksl");
	}

	public void setReturnDate(java.util.Date returnDate) {
		set("return_date", returnDate);
	}

	public java.util.Date getReturnDate() {
		return get("return_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

}
