package com.jfinalshop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ad", "id", Ad.class);
		arp.addMapping("ad_position", "id", AdPosition.class);
		arp.addMapping("ad_type", "id", AdType.class);
		arp.addMapping("admin", "id", Admin.class);
		// Composite Primary Key order: admins,roles
		arp.addMapping("admin_role", "admins,roles", AdminRole.class);
		arp.addMapping("agricultural_production", "id", AgriculturalProduction.class);
		arp.addMapping("appversion", "id", Appversion.class);
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_category", "id", ArticleCategory.class);
		arp.addMapping("article_eva", "id", ArticleEva.class);
		// Composite Primary Key order: articles,tags
		arp.addMapping("article_tag", "articles,tags", ArticleTag.class);
		arp.addMapping("atcrecord", "id", Atcrecord.class);
		arp.addMapping("attribute", "id", Attribute.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("cart", "id", Cart.class);
		arp.addMapping("cart_item", "id", CartItem.class);
		arp.addMapping("chosen_type", "id", ChosenType.class);
		arp.addMapping("client_ad", "id", ClientAd.class);
		arp.addMapping("client_boot", "id", ClientBoot.class);
		arp.addMapping("common_problem", "id", CommonProblem.class);
		arp.addMapping("consultation", "id", Consultation.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("coupon_code", "id", CouponCode.class);
		arp.addMapping("delivery_center", "id", DeliveryCenter.class);
		arp.addMapping("delivery_corp", "id", DeliveryCorp.class);
		arp.addMapping("delivery_template", "id", DeliveryTemplate.class);
		arp.addMapping("deposit_log", "id", DepositLog.class);
		arp.addMapping("dz_type", "id", DzType.class);
		arp.addMapping("enshrine", "id", Enshrine.class);
		arp.addMapping("evalueate", "id", Evalueate.class);
		arp.addMapping("field", "id", Field.class);
		arp.addMapping("field_type", "id", FieldType.class);
		arp.addMapping("freight_config", "id", FreightConfig.class);
		arp.addMapping("friend_link", "id", FriendLink.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("goods_eva", "id", GoodsEva.class);
		// Composite Primary Key order: goods,promotions
		arp.addMapping("goods_promotion", "goods,promotions", GoodsPromotion.class);
		// Composite Primary Key order: goods,tags
		arp.addMapping("goods_tag", "goods,tags", GoodsTag.class);
		arp.addMapping("income_stream", "id", IncomeStream.class);
		arp.addMapping("integral_stream", "id", IntegralStream.class);
		arp.addMapping("level", "id", Level.class);
		arp.addMapping("level_clause", "id", LevelClause.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("member_attribute", "id", MemberAttribute.class);
		arp.addMapping("member_eva", "id", MemberEva.class);
		// Composite Primary Key order: favorite_goods,favorite_members
		arp.addMapping("member_favorite_goods", "favorite_goods,favorite_members", MemberFavoriteGoods.class);
		arp.addMapping("member_rank", "id", MemberRank.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("message_config", "id", MessageConfig.class);
		arp.addMapping("message_copy", "id", MessageCopy.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_item", "id", OrderItem.class);
		arp.addMapping("order_item_copy", "id", OrderItemCopy.class);
		arp.addMapping("order_log", "id", OrderLog.class);
		arp.addMapping("order_new", "id", OrderNew.class);
		arp.addMapping("other_play", "id", OtherPlay.class);
		arp.addMapping("other_play_type", "id", OtherPlayType.class);
		arp.addMapping("parameter", "id", Parameter.class);
		arp.addMapping("payment", "id", Payment.class);
		arp.addMapping("payment_log", "id", PaymentLog.class);
		arp.addMapping("payment_method", "id", PaymentMethod.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("permission_group", "id", PermissionGroup.class);
		// Composite Primary Key order: permissions,roles
		arp.addMapping("permission_role", "permissions,roles", PermissionRole.class);
		arp.addMapping("play_type", "id", PlayType.class);
		arp.addMapping("plugin_config", "id", PluginConfig.class);
		arp.addMapping("point_log", "id", PointLog.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("product_category", "id", ProductCategory.class);
		// Composite Primary Key order: brands,product_categories
		arp.addMapping("product_category_brand", "brands,product_categories", ProductCategoryBrand.class);
		// Composite Primary Key order: product_categories,promotions
		arp.addMapping("product_category_promotion", "product_categories,promotions", ProductCategoryPromotion.class);
		arp.addMapping("product_notify", "id", ProductNotify.class);
		arp.addMapping("promotion", "id", Promotion.class);
		// Composite Primary Key order: coupons,promotions
		arp.addMapping("promotion_coupon", "coupons,promotions", PromotionCoupon.class);
		// Composite Primary Key order: gift_promotions,gifts
		arp.addMapping("promotion_gift", "gift_promotions,gifts", PromotionGift.class);
		// Composite Primary Key order: member_ranks,promotions
		arp.addMapping("promotion_member_rank", "member_ranks,promotions", PromotionMemberRank.class);
		arp.addMapping("receiver", "id", Receiver.class);
		arp.addMapping("recharge_combo", "id", RechargeCombo.class);
		arp.addMapping("refunds", "id", Refunds.class);
		arp.addMapping("returns", "id", Returns.class);
		arp.addMapping("returns_item", "id", ReturnsItem.class);
		arp.addMapping("review", "id", Review.class);
		arp.addMapping("review_great", "id", ReviewGreat.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("s_card", "id", SCard.class);
		arp.addMapping("s_cardmonth", "id", SCardmonth.class);
		arp.addMapping("s_cardorder", "id", SCardorder.class);
		arp.addMapping("s_comment", "id", SComment.class);
		arp.addMapping("s_recommend", "id", SRecommend.class);
		arp.addMapping("screen_type", "id", ScreenType.class);
		arp.addMapping("search_record", "sid", SearchRecord.class);
		arp.addMapping("seo", "id", Seo.class);
		arp.addMapping("ses_chosen", "id", SesChosen.class);
		arp.addMapping("ses_platform", "id", SesPlatform.class);
		arp.addMapping("ses_store", "id", SesStore.class);
		arp.addMapping("share", "id", Share.class);
		arp.addMapping("shipping", "id", Shipping.class);
		arp.addMapping("shipping_item", "id", ShippingItem.class);
		arp.addMapping("shipping_method", "id", ShippingMethod.class);
		// Composite Primary Key order: payment_methods,shipping_methods
		arp.addMapping("shipping_payment_method", "payment_methods,shipping_methods", ShippingPaymentMethod.class);
		arp.addMapping("sms", "id", Sms.class);
		arp.addMapping("sn", "id", Sn.class);
		arp.addMapping("special_good", "id", SpecialGood.class);
		arp.addMapping("specification", "id", Specification.class);
		arp.addMapping("statistic", "id", Statistic.class);
		arp.addMapping("stock_log", "id", StockLog.class);
		arp.addMapping("store_eva", "id", StoreEva.class);
		arp.addMapping("store_type", "id", StoreType.class);
		arp.addMapping("tag", "id", Tag.class);
		arp.addMapping("user_collection_goods", "id", UserCollectionGoods.class);
		arp.addMapping("user_collection_shop", "id", UserCollectionShop.class);
		arp.addMapping("user_footprint", "id", UserFootprint.class);
	}
}

