package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseAdType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdType extends BaseAdType<AdType> {
	public static final AdType dao = new AdType().dao();
}
