package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseAppversion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Appversion extends BaseAppversion<Appversion> {
	public static final Appversion dao = new Appversion().dao();
}
