package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseArticleEva;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleEva extends BaseArticleEva<ArticleEva> {
	public static final ArticleEva dao = new ArticleEva().dao();
}
