package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseAtcrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Atcrecord extends BaseAtcrecord<Atcrecord> {
	public static final Atcrecord dao = new Atcrecord().dao();
	
	public  enum Status {
		   UnReceive,Received;
	}
	public static enum  Type{
		/**
		 * dividend 每日分红 reg 注册福利
		 */
		Dividend(1,"红利"),Reg(2,"注册礼包");
		 int   index;
		 String name;
		Type(int index ,String name){
			this.index=index;
			this.name=name;
		}
		public int getIndex() {
			return index;
		}
		public void setIndex(int index) {
			this.index = index;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
	
	}
}
