package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseChosenType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChosenType extends BaseChosenType<ChosenType> {
	public static final ChosenType dao = new ChosenType().dao();
}
