package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseClientBoot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientBoot extends BaseClientBoot<ClientBoot> {
	public static final ClientBoot dao = new ClientBoot().dao();
}
