package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseCommonProblem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonProblem extends BaseCommonProblem<CommonProblem> {
	public static final CommonProblem dao = new CommonProblem().dao();
}
