package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseDzType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DzType extends BaseDzType<DzType> {
	public static final DzType dao = new DzType().dao();
}
