package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseEnshrine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enshrine extends BaseEnshrine<Enshrine> {
		public enum Type{
			store(1,"商店",'s'),field(3,"基地",'f'),other(2,"其他",'g');
			 Type(int index,String name,char signal) {
				this.index=index;
				this.name=name;
				this.symbol=signal;
			}
			 
			 public Type getType(int index) {
				    for(Type t:Type.values()) {
				    	 if(t.getIndex()==index) {
				    		 return t;
				    	 }
				    }
				    return null;
			 }
			 public Type getType(String name) {
				 for(Type t:Type.values()) {
					 if(t.getName().equals(name))return t;
				 }
				 return null;
			 }
			private int index;
			private String name;
			private  char symbol;
			public int getIndex() {
				return index;
			}
			public void setIndex(int index) {
				this.index = index;
			}
			public String getName() {
				return name;
			}
			public void setName(String name) {
				this.name = name;
			}
			public char getSymbol() {
				return symbol;
			}
			public void setSymbol(char symbol) {
				this.symbol = symbol;
			}
			
			
			
		}
		
	public static final Enshrine dao = new Enshrine().dao();
}
