package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseEvalueate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Evalueate extends BaseEvalueate<Evalueate> {
	public static final Evalueate dao = new Evalueate().dao();
}
