package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseFieldType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FieldType extends BaseFieldType<FieldType> {
	public static final FieldType dao = new FieldType().dao();
}
