package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseGoodsEva;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsEva extends BaseGoodsEva<GoodsEva> {
	public static final GoodsEva dao = new GoodsEva().dao();
}
