package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseIncomeStream;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IncomeStream extends BaseIncomeStream<IncomeStream> {
	public static final IncomeStream dao = new IncomeStream().dao();
}
