package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseIntegralStream;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralStream extends BaseIntegralStream<IntegralStream> {
	public static final IntegralStream dao = new IntegralStream().dao();
}
