package com.jfinalshop.model;

import java.util.List;

import com.jfinalshop.model.base.BaseLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Level extends BaseLevel<Level> {
	public static final Level dao = new Level().dao();
	
	public List<LevelClause> getClause(){
	     List<LevelClause> clause=LevelClause.dao.find("select  clause from  level_clause where level_id=?",this.getId());
	    return clause;
	}
}
