package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseLevelClause;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LevelClause extends BaseLevelClause<LevelClause> {
	public static final LevelClause dao = new LevelClause().dao();
}
