package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMemberEva;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberEva extends BaseMemberEva<MemberEva> {
	public static final MemberEva dao = new MemberEva().dao();
}
