package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMessageCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageCopy extends BaseMessageCopy<MessageCopy> {
	public static final MessageCopy dao = new MessageCopy().dao();
}
