package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseOrderNew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderNew extends BaseOrderNew<OrderNew> {
	public static final OrderNew dao = new OrderNew().dao();
}
