package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseOrderItemCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItemCopy extends BaseOrderItemCopy<OrderItemCopy> {
	public static final OrderItemCopy dao = new OrderItemCopy().dao();
}
