package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseOtherPlayType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OtherPlayType extends BaseOtherPlayType<OtherPlayType> {
	public static final OtherPlayType dao = new OtherPlayType().dao();
}
