package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseOtherPlay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OtherPlay extends BaseOtherPlay<OtherPlay> {
	
	

	public static final OtherPlay dao = new OtherPlay().dao();
	
	public enum Statu{
		use(1,"使用中"),forbidden(2,"被禁用");
		 Statu(int  i,String n) {
			 index=i;
			 name=n;
		}
	  private int index;
		private String name;
		public int getIndex() {
			return index;
		}
		public void setIndex(int index) {
			this.index = index;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		
		
	}
}
