package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePermissionGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionGroup extends BasePermissionGroup<PermissionGroup> {
	public static final PermissionGroup dao = new PermissionGroup().dao();
}
