package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePlayType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlayType extends BasePlayType<PlayType> {
	public static final PlayType dao = new PlayType().dao();
}
