package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseRechargeCombo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargeCombo extends BaseRechargeCombo<RechargeCombo> {
	public static final RechargeCombo dao = new RechargeCombo().dao();
}
