package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseReviewGreat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReviewGreat extends BaseReviewGreat<ReviewGreat> {
	public static final ReviewGreat dao = new ReviewGreat().dao();
	
	
}
