package com.jfinalshop.model;

import com.jfinal.aop.Enhancer;
import com.jfinalshop.dao.PaymentLogDao;
import com.jfinalshop.model.base.BaseSCardorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCardorder extends BaseSCardorder<SCardorder> {
	public static final SCardorder dao = new SCardorder().dao();
	private PaymentLogDao paymentLogDao = Enhancer.enhance(PaymentLogDao.class);
	
	public enum Status{
		/**
		 * wait 等待支付 pay 已支付 outtime 已到期 renewwal 已续期
		 */
		wait(0,"等待支付"),pay(1,"已支付"),outTime(3,"已到期"),refund(4,"退卡"),renewal(6,"续期");
		
		private int index;
		private String desc;
		Status(int index,String desc){
			this.index=index;
			this.desc=desc;
		}
		public int getIndex() {
			return index;
		}
		public void setIndex(int index) {
			this.index = index;
		}
		public String getDesc() {
			return desc;
		}
		public void setDesc(String desc) {
			this.desc = desc;
		}
		
		
	}
	/** 会员 */
	private Member member;
	
	private PaymentLog cardmpaymentLog;//购卡支付记录
	
	

	public PaymentLog getCardmpaymentLog() {
		if (cardmpaymentLog == null) {
			cardmpaymentLog = paymentLogDao.findByCardorderId(getId());
		}
		return cardmpaymentLog;
	}


	/**
	 * 获取会员
	 * 
	 * @return 会员
	 */
	public Member getMember() {
		
		if (member == null) {
			member = Member.dao.findById(getMemberId());
		}
		return member;
	}
	
	
	/**
	 * 设置会员
	 * 
	 * @param card
	 *            会员
	 */
	public void setMember(Member member) {
		this.member = member;
	}
	
	
	
	/** 会员卡 */
	private SCard card;
	
	
	/**
	 * 获取会员卡
	 * 
	 * @return 会员卡
	 */
	public SCard getCard() {
		if (card == null) {
			card = SCard.dao.findById(getCardId());
		}
		return card;
	}
	
	
	/**
	 * 设置会员卡类
	 * 
	 * @param card
	 *            会员卡
	 */
	public void setCard(SCard card) {
		this.card = card;
	}
	
}
