package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSCard;

/**
 * Generated by JFinal.
 */
public class SCard extends BaseSCard<SCard> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final SCard dao = new SCard();
}
