package com.jfinalshop.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.jfinalshop.model.base.BaseSComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SComment extends BaseSComment<SComment> {
	public static final SComment dao = new SComment().dao();
	
	public enum Type{
		/**
		 * sayGoods 点赞 comment 评论 取ordinal存放在数据库
		 */
		SayGoods,Comment,SubComment,SubPraise
	}
	
	public enum Level{
		Independent,Clause
	}
	
	public  List  getSubComment(long id,long  sid) {
		 List<Record> rs=Db.find("select  m.portrait,m.nickname,s.comment_str as comment  from member m inner join s_comment s "
		 		+ "   on  s.member_id=m.id and s.appender_id=? and s.type=?  and append_comment_id=?",id,Type.SubComment.ordinal(),sid);
		return rs;
	}
}
