package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseScreenType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScreenType extends BaseScreenType<ScreenType> {
	public static final ScreenType dao = new ScreenType().dao();
}
