package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSearchRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SearchRecord extends BaseSearchRecord<SearchRecord> {
	public static final SearchRecord dao = new SearchRecord().dao();
	
   public enum Type{
	      store(0,"店铺"),goods(1,"商品"),article(2,"资讯");
	   
	   private int index;
	   private String name;
	   Type(int index,String name){
		   this.index=index;
		   this.name=name;
	   }
	
	public int getIndex() {
		return index;
	}
	public void setIndex(int index) {
		this.index = index;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
   }
   
   public enum TopOrder{
	   Ordinary("未置顶"),First("第一位"),Second("第二位"),Third("第三位"),Fourth("第四位"),Fifth("第五位");
	   private String name;
	   TopOrder(String name){
		   this.name=name;
	   }
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
   }
   
}
