package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSesChosen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SesChosen extends BaseSesChosen<SesChosen> {
	public static final SesChosen dao = new SesChosen().dao();
}
