package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSesPlatform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SesPlatform extends BaseSesPlatform<SesPlatform> {
	public static final SesPlatform dao = new SesPlatform().dao();
}
