package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Share extends BaseShare<Share> {
	public static final Share dao = new Share().dao();
}
