package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSpecialGood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialGood extends BaseSpecialGood<SpecialGood> {
	public static final SpecialGood dao = new SpecialGood().dao();
}
