package com.jfinalshop.model;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.jfinalshop.dao.SCardRecommendDao;
import com.jfinalshop.model.base.BaseSRecommend;
import com.jfinalshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRecommend extends BaseSRecommend<SRecommend> {
	public static final SCardRecommendDao dao = new SCardRecommendDao();
	
	
	/** 推荐人 */
	private Member member;
	/** 一级被推荐人 */
	private Member tomember;
	
	/** 二级被推荐人 */
	private Member totomember;

	/**
	 * 获取会员
	 * 
	 * @return 会员
	 */
	public Member getMember() {
		if (ObjectUtils.isEmpty(member)) {
			member = Member.dao.findById(getMemberId());
		}
		return member;
	}

	public Member getTomember() {
		if (ObjectUtils.isEmpty(tomember)) {
			tomember = Member.dao.findById(getToMemberId());
		}
		return tomember;
	}

	public Member getTotomember() {
		try {
			if (!ObjectUtils.isEmpty(member)) {
				if (!ObjectUtils.isEmpty(dao.findByTomemberidTwo(member.getId()))) {
				totomember=dao.findByTomemberidTwo(member.getId()).getMember();
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return totomember;
	}
	
	
	

}
