package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseStoreEva;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreEva extends BaseStoreEva<StoreEva> {
	public static final StoreEva dao = new StoreEva().dao();
}
