package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseStoreType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreType extends BaseStoreType<StoreType> {
	public static final StoreType dao = new StoreType().dao();
}
