package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseUserCollectionShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCollectionShop extends BaseUserCollectionShop<UserCollectionShop> {
	public static final UserCollectionShop dao = new UserCollectionShop().dao();
}
