package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseUserProblems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProblems extends BaseUserProblems<UserProblems> {
	public static final UserProblems dao = new UserProblems().dao();
}
