package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseUserCollectionGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCollectionGoods extends BaseUserCollectionGoods<UserCollectionGoods> {
	public static final UserCollectionGoods dao = new UserCollectionGoods().dao();
}
