package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseUserFootprint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFootprint extends BaseUserFootprint<UserFootprint> {
	public static final UserFootprint dao = new UserFootprint().dao();
}
