package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseUserAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAnswer extends BaseUserAnswer<UserAnswer> {
	public static final UserAnswer dao = new UserAnswer().dao();
}
