package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseAdPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdPosition extends BaseAdPosition<AdPosition> {
	public static final AdPosition dao = new AdPosition().dao();
}
