package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area().dao();
}
