package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseArticleTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleTag extends BaseArticleTag<ArticleTag> {
	public static final ArticleTag dao = new ArticleTag().dao();
}
