package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseArticleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCategory extends BaseArticleCategory<ArticleCategory> {
	public static final ArticleCategory dao = new ArticleCategory().dao();
}
