package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseAtcrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Atcrecord extends BaseAtcrecord<Atcrecord> {
	public static final Atcrecord dao = new Atcrecord().dao();
}
