package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseCartItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CartItem extends BaseCartItem<CartItem> {
	public static final CartItem dao = new CartItem().dao();
}
