package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseConsultation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Consultation extends BaseConsultation<Consultation> {
	public static final Consultation dao = new Consultation().dao();
}
