package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseCouponCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponCode extends BaseCouponCode<CouponCode> {
	public static final CouponCode dao = new CouponCode().dao();
}
