package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseDeliveryCenter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryCenter extends BaseDeliveryCenter<DeliveryCenter> {
	public static final DeliveryCenter dao = new DeliveryCenter().dao();
}
