package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseDeliveryTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryTemplate extends BaseDeliveryTemplate<DeliveryTemplate> {
	public static final DeliveryTemplate dao = new DeliveryTemplate().dao();
}
