package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseDepositLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepositLog extends BaseDepositLog<DepositLog> {
	public static final DepositLog dao = new DepositLog().dao();
}
