package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseGoodsPromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsPromotion extends BaseGoodsPromotion<GoodsPromotion> {
	public static final GoodsPromotion dao = new GoodsPromotion().dao();
}
