package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseGoodsTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsTag extends BaseGoodsTag<GoodsTag> {
	public static final GoodsTag dao = new GoodsTag().dao();
}
