package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMemberFavoriteGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberFavoriteGoods extends BaseMemberFavoriteGoods<MemberFavoriteGoods> {
	public static final MemberFavoriteGoods dao = new MemberFavoriteGoods().dao();
}
