package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMemberRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberRank extends BaseMemberRank<MemberRank> {
	public static final MemberRank dao = new MemberRank().dao();
}
