package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMemberAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberAttribute extends BaseMemberAttribute<MemberAttribute> {
	public static final MemberAttribute dao = new MemberAttribute().dao();
}
