package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMessageConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageConfig extends BaseMessageConfig<MessageConfig> {
	public static final MessageConfig dao = new MessageConfig().dao();
}
