package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLog extends BaseOrderLog<OrderLog> {
	public static final OrderLog dao = new OrderLog().dao();
}
