package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parameter extends BaseParameter<Parameter> {
	public static final Parameter dao = new Parameter().dao();
}
