package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payment extends BasePayment<Payment> {
	public static final Payment dao = new Payment().dao();
}
