package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePaymentLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentLog extends BasePaymentLog<PaymentLog> {
	public static final PaymentLog dao = new PaymentLog().dao();
}
