package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePaymentMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentMethod extends BasePaymentMethod<PaymentMethod> {
	public static final PaymentMethod dao = new PaymentMethod().dao();
}
