package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePermissionRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionRole extends BasePermissionRole<PermissionRole> {
	public static final PermissionRole dao = new PermissionRole().dao();
}
