package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePluginConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PluginConfig extends BasePluginConfig<PluginConfig> {
	public static final PluginConfig dao = new PluginConfig().dao();
}
