package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePointLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointLog extends BasePointLog<PointLog> {
	public static final PointLog dao = new PointLog().dao();
}
