package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseProductCategoryBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategoryBrand extends BaseProductCategoryBrand<ProductCategoryBrand> {
	public static final ProductCategoryBrand dao = new ProductCategoryBrand().dao();
}
