package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	public static final ProductCategory dao = new ProductCategory().dao();
}
