package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseProductCategoryPromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategoryPromotion extends BaseProductCategoryPromotion<ProductCategoryPromotion> {
	public static final ProductCategoryPromotion dao = new ProductCategoryPromotion().dao();
}
