package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseProductNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductNotify extends BaseProductNotify<ProductNotify> {
	public static final ProductNotify dao = new ProductNotify().dao();
}
