package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Promotion extends BasePromotion<Promotion> {
	public static final Promotion dao = new Promotion().dao();
}
