package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePromotionMemberRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionMemberRank extends BasePromotionMemberRank<PromotionMemberRank> {
	public static final PromotionMemberRank dao = new PromotionMemberRank().dao();
}
