package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePromotionGift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionGift extends BasePromotionGift<PromotionGift> {
	public static final PromotionGift dao = new PromotionGift().dao();
}
