package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePromotionCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionCoupon extends BasePromotionCoupon<PromotionCoupon> {
	public static final PromotionCoupon dao = new PromotionCoupon().dao();
}
