package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseRefunds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Refunds extends BaseRefunds<Refunds> {
	public static final Refunds dao = new Refunds().dao();
}
