package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseReturns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returns extends BaseReturns<Returns> {
	public static final Returns dao = new Returns().dao();
}
