package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseReturnsItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnsItem extends BaseReturnsItem<ReturnsItem> {
	public static final ReturnsItem dao = new ReturnsItem().dao();
}
