package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCard extends BaseSCard<SCard> {
	public static final SCard dao = new SCard().dao();
}
