package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSCardorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCardorder extends BaseSCardorder<SCardorder> {
	public static final SCardorder dao = new SCardorder().dao();
}
