package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSCardmonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCardmonth extends BaseSCardmonth<SCardmonth> {
	public static final SCardmonth dao = new SCardmonth().dao();
}
