package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSeo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seo extends BaseSeo<Seo> {
	public static final Seo dao = new Seo().dao();
}
