package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseShippingItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingItem extends BaseShippingItem<ShippingItem> {
	public static final ShippingItem dao = new ShippingItem().dao();
}
