package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseShippingMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingMethod extends BaseShippingMethod<ShippingMethod> {
	public static final ShippingMethod dao = new ShippingMethod().dao();
}
