package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseShippingPaymentMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingPaymentMethod extends BaseShippingPaymentMethod<ShippingPaymentMethod> {
	public static final ShippingPaymentMethod dao = new ShippingPaymentMethod().dao();
}
