package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sms extends BaseSms<Sms> {
	public static final Sms dao = new Sms().dao();
}
