package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseSRecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRecommend extends BaseSRecommend<SRecommend> {
	public static final SRecommend dao = new SRecommend().dao();
}
