package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseStatistic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statistic extends BaseStatistic<Statistic> {
	public static final Statistic dao = new Statistic().dao();
}
