package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseStockLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockLog extends BaseStockLog<StockLog> {
	public static final StockLog dao = new StockLog().dao();
}
