package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
	public static final Tag dao = new Tag().dao();
}
