package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setAttributeValue0(java.lang.String attributeValue0) {
		set("attribute_value0", attributeValue0);
	}

	public java.lang.String getAttributeValue0() {
		return get("attribute_value0");
	}

	public void setAttributeValue1(java.lang.String attributeValue1) {
		set("attribute_value1", attributeValue1);
	}

	public java.lang.String getAttributeValue1() {
		return get("attribute_value1");
	}

	public void setAttributeValue10(java.lang.String attributeValue10) {
		set("attribute_value10", attributeValue10);
	}

	public java.lang.String getAttributeValue10() {
		return get("attribute_value10");
	}

	public void setAttributeValue11(java.lang.String attributeValue11) {
		set("attribute_value11", attributeValue11);
	}

	public java.lang.String getAttributeValue11() {
		return get("attribute_value11");
	}

	public void setAttributeValue12(java.lang.String attributeValue12) {
		set("attribute_value12", attributeValue12);
	}

	public java.lang.String getAttributeValue12() {
		return get("attribute_value12");
	}

	public void setAttributeValue13(java.lang.String attributeValue13) {
		set("attribute_value13", attributeValue13);
	}

	public java.lang.String getAttributeValue13() {
		return get("attribute_value13");
	}

	public void setAttributeValue14(java.lang.String attributeValue14) {
		set("attribute_value14", attributeValue14);
	}

	public java.lang.String getAttributeValue14() {
		return get("attribute_value14");
	}

	public void setAttributeValue15(java.lang.String attributeValue15) {
		set("attribute_value15", attributeValue15);
	}

	public java.lang.String getAttributeValue15() {
		return get("attribute_value15");
	}

	public void setAttributeValue16(java.lang.String attributeValue16) {
		set("attribute_value16", attributeValue16);
	}

	public java.lang.String getAttributeValue16() {
		return get("attribute_value16");
	}

	public void setAttributeValue17(java.lang.String attributeValue17) {
		set("attribute_value17", attributeValue17);
	}

	public java.lang.String getAttributeValue17() {
		return get("attribute_value17");
	}

	public void setAttributeValue18(java.lang.String attributeValue18) {
		set("attribute_value18", attributeValue18);
	}

	public java.lang.String getAttributeValue18() {
		return get("attribute_value18");
	}

	public void setAttributeValue19(java.lang.String attributeValue19) {
		set("attribute_value19", attributeValue19);
	}

	public java.lang.String getAttributeValue19() {
		return get("attribute_value19");
	}

	public void setAttributeValue2(java.lang.String attributeValue2) {
		set("attribute_value2", attributeValue2);
	}

	public java.lang.String getAttributeValue2() {
		return get("attribute_value2");
	}

	public void setAttributeValue3(java.lang.String attributeValue3) {
		set("attribute_value3", attributeValue3);
	}

	public java.lang.String getAttributeValue3() {
		return get("attribute_value3");
	}

	public void setAttributeValue4(java.lang.String attributeValue4) {
		set("attribute_value4", attributeValue4);
	}

	public java.lang.String getAttributeValue4() {
		return get("attribute_value4");
	}

	public void setAttributeValue5(java.lang.String attributeValue5) {
		set("attribute_value5", attributeValue5);
	}

	public java.lang.String getAttributeValue5() {
		return get("attribute_value5");
	}

	public void setAttributeValue6(java.lang.String attributeValue6) {
		set("attribute_value6", attributeValue6);
	}

	public java.lang.String getAttributeValue6() {
		return get("attribute_value6");
	}

	public void setAttributeValue7(java.lang.String attributeValue7) {
		set("attribute_value7", attributeValue7);
	}

	public java.lang.String getAttributeValue7() {
		return get("attribute_value7");
	}

	public void setAttributeValue8(java.lang.String attributeValue8) {
		set("attribute_value8", attributeValue8);
	}

	public java.lang.String getAttributeValue8() {
		return get("attribute_value8");
	}

	public void setGoodsUrl(java.lang.String goodsUrl) {
		set("goods_url", goodsUrl);
	}

	public java.lang.String getGoodsUrl() {
		return get("goods_url");
	}

	public void setCaption(java.lang.String caption) {
		set("caption", caption);
	}

	public java.lang.String getCaption() {
		return get("caption");
	}

	public void setGenerateMethod(java.lang.Integer generateMethod) {
		set("generate_method", generateMethod);
	}

	public java.lang.Integer getGenerateMethod() {
		return get("generate_method");
	}

	public void setHits(java.lang.Long hits) {
		set("hits", hits);
	}

	public java.lang.Long getHits() {
		return get("hits");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public void setIsDelivery(java.lang.Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}

	public java.lang.Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setIsList(java.lang.Boolean isList) {
		set("is_list", isList);
	}

	public java.lang.Boolean getIsList() {
		return get("is_list");
	}

	public void setIsMarketable(java.lang.Boolean isMarketable) {
		set("is_marketable", isMarketable);
	}

	public java.lang.Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public void setIsTop(java.lang.Boolean isTop) {
		set("is_top", isTop);
	}

	public java.lang.Boolean getIsTop() {
		return get("is_top");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return get("keyword");
	}

	public void setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setMonthHits(java.lang.Long monthHits) {
		set("month_hits", monthHits);
	}

	public java.lang.Long getMonthHits() {
		return get("month_hits");
	}

	public void setMonthHitsDate(java.util.Date monthHitsDate) {
		set("month_hits_date", monthHitsDate);
	}

	public java.util.Date getMonthHitsDate() {
		return get("month_hits_date");
	}

	public void setMonthSales(java.lang.Long monthSales) {
		set("month_sales", monthSales);
	}

	public java.lang.Long getMonthSales() {
		return get("month_sales");
	}

	public void setMonthSalesDate(java.util.Date monthSalesDate) {
		set("month_sales_date", monthSalesDate);
	}

	public java.util.Date getMonthSalesDate() {
		return get("month_sales_date");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setParameterValues(java.lang.String parameterValues) {
		set("parameter_values", parameterValues);
	}

	public java.lang.String getParameterValues() {
		return get("parameter_values");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setProductImages(java.lang.String productImages) {
		set("product_images", productImages);
	}

	public java.lang.String getProductImages() {
		return get("product_images");
	}

	public void setSales(java.lang.Long sales) {
		set("sales", sales);
	}

	public java.lang.Long getSales() {
		return get("sales");
	}

	public void setScore(java.lang.Float score) {
		set("score", score);
	}

	public java.lang.Float getScore() {
		return get("score");
	}

	public void setScoreCount(java.lang.Long scoreCount) {
		set("score_count", scoreCount);
	}

	public java.lang.Long getScoreCount() {
		return get("score_count");
	}

	public void setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
	}

	public java.lang.String getSeoDescription() {
		return get("seo_description");
	}

	public void setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	public java.lang.String getSeoKeywords() {
		return get("seo_keywords");
	}

	public void setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
	}

	public java.lang.String getSeoTitle() {
		return get("seo_title");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setSpecificationItems(java.lang.String specificationItems) {
		set("specification_items", specificationItems);
	}

	public java.lang.String getSpecificationItems() {
		return get("specification_items");
	}

	public void setTotalScore(java.lang.Long totalScore) {
		set("total_score", totalScore);
	}

	public java.lang.Long getTotalScore() {
		return get("total_score");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setWeekHits(java.lang.Long weekHits) {
		set("week_hits", weekHits);
	}

	public java.lang.Long getWeekHits() {
		return get("week_hits");
	}

	public void setWeekHitsDate(java.util.Date weekHitsDate) {
		set("week_hits_date", weekHitsDate);
	}

	public java.util.Date getWeekHitsDate() {
		return get("week_hits_date");
	}

	public void setWeekSales(java.lang.Long weekSales) {
		set("week_sales", weekSales);
	}

	public java.lang.Long getWeekSales() {
		return get("week_sales");
	}

	public void setWeekSalesDate(java.util.Date weekSalesDate) {
		set("week_sales_date", weekSalesDate);
	}

	public java.util.Date getWeekSalesDate() {
		return get("week_sales_date");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setBrandId(java.lang.Long brandId) {
		set("brand_id", brandId);
	}

	public java.lang.Long getBrandId() {
		return get("brand_id");
	}

	public void setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public java.lang.Long getProductCategoryId() {
		return get("product_category_id");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}

	public java.lang.String getOrigin() {
		return get("origin");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return get("number");
	}

	public void setOnlineurl(java.lang.String onlineurl) {
		set("onlineurl", onlineurl);
	}

	public java.lang.String getOnlineurl() {
		return get("onlineurl");
	}

	public void setIsDz(java.lang.String isDz) {
		set("is_dz", isDz);
	}

	public java.lang.String getIsDz() {
		return get("is_dz");
	}

	public void setCycle(java.lang.Integer cycle) {
		set("cycle", cycle);
	}

	public java.lang.Integer getCycle() {
		return get("cycle");
	}

	public void setDzTypeId(java.lang.Integer dzTypeId) {
		set("dz_type_id", dzTypeId);
	}

	public java.lang.Integer getDzTypeId() {
		return get("dz_type_id");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return get("store_id");
	}

	public void setProductDate(java.util.Date productDate) {
		set("product_date", productDate);
	}

	public java.util.Date getProductDate() {
		return get("product_date");
	}

	public void setStype(java.lang.String stype) {
		set("stype", stype);
	}

	public java.lang.String getStype() {
		return get("stype");
	}

	public void setReleaseDate(java.lang.Integer releaseDate) {
		set("release_date", releaseDate);
	}

	public java.lang.Integer getReleaseDate() {
		return get("release_date");
	}

	public void setAttributeValue9(java.lang.String attributeValue9) {
		set("attribute_value9", attributeValue9);
	}

	public java.lang.String getAttributeValue9() {
		return get("attribute_value9");
	}

	public void setIsCollect(java.lang.Long isCollect) {
		set("is_collect", isCollect);
	}

	public java.lang.Long getIsCollect() {
		return get("is_collect");
	}

}
