package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLevelClause<M extends BaseLevelClause<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setClause(java.lang.String clause) {
		set("clause", clause);
	}

	public java.lang.String getClause() {
		return get("clause");
	}

	public void setLevelId(java.lang.Long levelId) {
		set("level_id", levelId);
	}

	public java.lang.Long getLevelId() {
		return get("level_id");
	}

}
