package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCollectionShop<M extends BaseUserCollectionShop<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMecreateDate(java.util.Date mecreateDate) {
		set("mecreate_date", mecreateDate);
	}

	public java.util.Date getMecreateDate() {
		return get("mecreate_date");
	}

	public void setSesStoreId(java.lang.Long sesStoreId) {
		set("ses_store_id", sesStoreId);
	}

	public java.lang.Long getSesStoreId() {
		return get("ses_store_id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

}
