package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSesChosen<M extends BaseSesChosen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("store_id");
	}

	public void setChosenId(java.lang.Integer chosenId) {
		set("chosen_id", chosenId);
	}

	public java.lang.Integer getChosenId() {
		return get("chosen_id");
	}

}
