package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSesStore<M extends BaseSesStore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSname(java.lang.String sname) {
		set("sname", sname);
	}

	public java.lang.String getSname() {
		return get("sname");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	public java.lang.String getDetail() {
		return get("detail");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}

	public java.lang.Integer getTypeId() {
		return get("type_id");
	}

	public void setScore(java.math.BigDecimal score) {
		set("score", score);
	}

	public java.math.BigDecimal getScore() {
		return get("score");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setJoindate(java.util.Date joindate) {
		set("joindate", joindate);
	}

	public java.util.Date getJoindate() {
		return get("joindate");
	}

	public void setPlayUrl(java.lang.String playUrl) {
		set("play_url", playUrl);
	}

	public java.lang.String getPlayUrl() {
		return get("play_url");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public void setSharecount(java.lang.Long sharecount) {
		set("sharecount", sharecount);
	}

	public java.lang.Long getSharecount() {
		return get("sharecount");
	}

	public void setTg(java.lang.String tg) {
		set("tg", tg);
	}

	public java.lang.String getTg() {
		return get("tg");
	}

	public void setOwner(java.lang.String owner) {
		set("owner", owner);
	}

	public java.lang.String getOwner() {
		return get("owner");
	}

	public void setImages(java.lang.String images) {
		set("images", images);
	}

	public java.lang.String getImages() {
		return get("images");
	}

	public void setStoreDiscount(java.lang.String storeDiscount) {
		set("store_discount", storeDiscount);
	}

	public java.lang.String getStoreDiscount() {
		return get("store_discount");
	}

	public void setLat(java.lang.Float lat) {
		set("lat", lat);
	}

	public java.lang.Float getLat() {
		return get("lat");
	}

	public void setLng(java.lang.Float lng) {
		set("lng", lng);
	}

	public java.lang.Float getLng() {
		return get("lng");
	}

	public void setTgId(java.lang.Long tgId) {
		set("tg_id", tgId);
	}

	public java.lang.Long getTgId() {
		return get("tg_id");
	}

	public void setBackground(java.lang.String background) {
		set("background", background);
	}

	public java.lang.String getBackground() {
		return get("background");
	}

	public void setProductType(java.lang.String productType) {
		set("product_type", productType);
	}

	public java.lang.String getProductType() {
		return get("product_type");
	}

	public void setMainOperation(java.lang.String mainOperation) {
		set("main_operation", mainOperation);
	}

	public java.lang.String getMainOperation() {
		return get("main_operation");
	}

	public void setOperationLicence(java.lang.String operationLicence) {
		set("operation_licence", operationLicence);
	}

	public java.lang.String getOperationLicence() {
		return get("operation_licence");
	}

	public void setContactMobile(java.lang.String contactMobile) {
		set("contact_mobile", contactMobile);
	}

	public java.lang.String getContactMobile() {
		return get("contact_mobile");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStoreImg(java.lang.String storeImg) {
		set("store_img", storeImg);
	}

	public java.lang.String getStoreImg() {
		return get("store_img");
	}

	public void setMarkMsg(java.lang.String markMsg) {
		set("markMsg", markMsg);
	}

	public java.lang.String getMarkMsg() {
		return get("markMsg");
	}

	public void setStoreUrl(java.lang.String storeUrl) {
		set("store_url", storeUrl);
	}

	public java.lang.String getStoreUrl() {
		return get("store_url");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

	public void setEnvironmentMsg(java.lang.String environmentMsg) {
		set("environmentMsg", environmentMsg);
	}

	public java.lang.String getEnvironmentMsg() {
		return get("environmentMsg");
	}

}
