package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShare<M extends BaseShare<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setForeignId(java.lang.Long foreignId) {
		set("foreign_id", foreignId);
	}

	public java.lang.Long getForeignId() {
		return get("foreign_id");
	}

	public void setPlatform(java.lang.Integer platform) {
		set("platform", platform);
	}

	public java.lang.Integer getPlatform() {
		return get("platform");
	}

	public void setCount(java.lang.Long count) {
		set("count", count);
	}

	public java.lang.Long getCount() {
		return get("count");
	}

}
