package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseField<M extends BaseField<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setPlayAdr(java.lang.String playAdr) {
		set("play_adr", playAdr);
	}

	public java.lang.String getPlayAdr() {
		return get("play_adr");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}

	public java.lang.Integer getTypeId() {
		return get("type_id");
	}

	public void setSharecount(java.lang.Long sharecount) {
		set("sharecount", sharecount);
	}

	public java.lang.Long getSharecount() {
		return get("sharecount");
	}

}
