package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRechargeCombo<M extends BaseRechargeCombo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCombo(java.lang.String combo) {
		set("combo", combo);
	}

	public java.lang.String getCombo() {
		return get("combo");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setCoupon(java.math.BigDecimal coupon) {
		set("coupon", coupon);
	}

	public java.math.BigDecimal getCoupon() {
		return get("coupon");
	}

}
