package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAgriculturalProduction<M extends BaseAgriculturalProduction<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAreaid(java.lang.Integer areaid) {
		set("areaid", areaid);
	}

	public java.lang.Integer getAreaid() {
		return get("areaid");
	}

	public void setAreaname(java.lang.String areaname) {
		set("areaname", areaname);
	}

	public java.lang.String getAreaname() {
		return get("areaname");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setProductType(java.lang.Integer productType) {
		set("product_type", productType);
	}

	public java.lang.Integer getProductType() {
		return get("product_type");
	}

	public void setMajorGood(java.lang.String majorGood) {
		set("major_good", majorGood);
	}

	public java.lang.String getMajorGood() {
		return get("major_good");
	}

	public void setProductCertification(java.lang.String productCertification) {
		set("product_certification", productCertification);
	}

	public java.lang.String getProductCertification() {
		return get("product_certification");
	}

	public void setCertificationUrl(java.lang.String certificationUrl) {
		set("certification_url", certificationUrl);
	}

	public java.lang.String getCertificationUrl() {
		return get("certification_url");
	}

	public void setBusinessLicence(java.lang.String businessLicence) {
		set("business_licence", businessLicence);
	}

	public java.lang.String getBusinessLicence() {
		return get("business_licence");
	}

	public void setOtherLicence(java.lang.String otherLicence) {
		set("other_licence", otherLicence);
	}

	public java.lang.String getOtherLicence() {
		return get("other_licence");
	}

	public void setBasePicture(java.lang.String basePicture) {
		set("base_picture", basePicture);
	}

	public java.lang.String getBasePicture() {
		return get("base_picture");
	}

	public void setVenderPicture(java.lang.String venderPicture) {
		set("vender_picture", venderPicture);
	}

	public java.lang.String getVenderPicture() {
		return get("vender_picture");
	}

	public void setStorePicture(java.lang.String storePicture) {
		set("store_picture", storePicture);
	}

	public java.lang.String getStorePicture() {
		return get("store_picture");
	}

	public void setLinkman(java.lang.String linkman) {
		set("linkman", linkman);
	}

	public java.lang.String getLinkman() {
		return get("linkman");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setProductImages(java.lang.String productImages) {
		set("product_images", productImages);
	}

	public java.lang.String getProductImages() {
		return get("product_images");
	}

}
