package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSComment<M extends BaseSComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

	public void setCommentStr(java.lang.String commentStr) {
		set("comment_str", commentStr);
	}

	public java.lang.String getCommentStr() {
		return get("comment_str");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setArticleId(java.lang.Long articleId) {
		set("article_id", articleId);
	}

	public java.lang.Long getArticleId() {
		return get("article_id");
	}

	public void setPraise(java.lang.Long praise) {
		set("praise", praise);
	}

	public java.lang.Long getPraise() {
		return get("praise");
	}

	public void setCDate(java.util.Date cDate) {
		set("c_date", cDate);
	}

	public java.util.Date getCDate() {
		return get("c_date");
	}

	public void setAppenderId(java.lang.Long appenderId) {
		set("appender_id", appenderId);
	}

	public java.lang.Long getAppenderId() {
		return get("appender_id");
	}

	public void setAppendCommentId(java.lang.Long appendCommentId) {
		set("append_comment_id", appendCommentId);
	}

	public java.lang.Long getAppendCommentId() {
		return get("append_comment_id");
	}

}
