package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSearchRecord<M extends BaseSearchRecord<M>> extends Model<M> implements IBean {

	public void setSid(java.lang.Long sid) {
		set("sid", sid);
	}

	public java.lang.Long getSid() {
		return get("sid");
	}

	public void setStext(java.lang.String stext) {
		set("stext", stext);
	}

	public java.lang.String getStext() {
		return get("stext");
	}

	public void setSsum(java.lang.Long ssum) {
		set("ssum", ssum);
	}

	public java.lang.Long getSsum() {
		return get("ssum");
	}

	public void setSearchType(java.lang.Integer searchType) {
		set("search_type", searchType);
	}

	public java.lang.Integer getSearchType() {
		return get("search_type");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return get("orders");
	}

}
