package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientAd<M extends BaseClientAd<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAdName(java.lang.String adName) {
		set("ad_name", adName);
	}

	public java.lang.String getAdName() {
		return get("ad_name");
	}

	public void setAdImg(java.lang.String adImg) {
		set("ad_img", adImg);
	}

	public java.lang.String getAdImg() {
		return get("ad_img");
	}

	public void setAdPath(java.lang.String adPath) {
		set("ad_path", adPath);
	}

	public java.lang.String getAdPath() {
		return get("ad_path");
	}

	public void setOperationEmployee(java.lang.Integer operationEmployee) {
		set("operation_employee", operationEmployee);
	}

	public java.lang.Integer getOperationEmployee() {
		return get("operation_employee");
	}

	public void setAdType(java.lang.Integer adType) {
		set("ad_type", adType);
	}

	public java.lang.Integer getAdType() {
		return get("ad_type");
	}

	public void setAdDate(java.util.Date adDate) {
		set("ad_date", adDate);
	}

	public java.util.Date getAdDate() {
		return get("ad_date");
	}

	public void setIsup(java.lang.Integer isup) {
		set("isup", isup);
	}

	public java.lang.Integer getIsup() {
		return get("isup");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	public java.lang.String getDetail() {
		return get("detail");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
