package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreEva<M extends BaseStoreEva<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("store_id");
	}

	public void setEvalueateId(java.lang.Integer evalueateId) {
		set("evalueate_id", evalueateId);
	}

	public java.lang.Integer getEvalueateId() {
		return get("evalueate_id");
	}

}
