package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOtherPlay<M extends BaseOtherPlay<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setPlayAdr(java.lang.String playAdr) {
		set("play_adr", playAdr);
	}

	public java.lang.String getPlayAdr() {
		return get("play_adr");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setIconAdr(java.lang.String iconAdr) {
		set("icon_adr", iconAdr);
	}

	public java.lang.String getIconAdr() {
		return get("icon_adr");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setOperationId(java.lang.Integer operationId) {
		set("operation_id", operationId);
	}

	public java.lang.Integer getOperationId() {
		return get("operation_id");
	}

	public void setSharecount(java.lang.Long sharecount) {
		set("sharecount", sharecount);
	}

	public java.lang.Long getSharecount() {
		return get("sharecount");
	}

}
